### ISSUE TITLE
hey i have bug plugin

### ISSUE THREAD

**Issue by OwnerSCIFahrul** [FoxValleyMC/TelegramUI#4]
"17:27:17 [FATAL] Could not pass event "cn.nukkit.event.player.PlayerFormRespondedEvent" to "TelegramUI v1.0.0": null on TelegramUI.Events.FormResponseEvent
17:27:17 [ERROR] Throwing
cn.nukkit.utils.EventException: null
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[Nukkit-Version-1.14.0.jar:?]
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[Nukkit-Version-1.14.0.jar:?]
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546) ~[Nukkit-Version-1.14.0.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:2609) ~[Nukkit-Version-1.14.0.jar:?]
        at java.util.ArrayList.forEach(Unknown Source) [?:1.8.0_202]
        at cn.nukkit.network.Network.processPackets(Network.java:197) [Nukkit-Version-1.14.0.jar:?]
        at cn.nukkit.network.Network.processBatch(Network.java:180) [Nukkit-Version-1.14.0.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:2092) [Nukkit-Version-1.14.0.jar:?]
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157) [Nukkit-Version-1.14.0.jar:?]
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132) [Nukkit-Version-1.14.0.jar:?]
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66) [Nukkit-Version-1.14.0.jar:?]
        at cn.nukkit.network.Network.processInterfaces(Network.java:83) [Nukkit-Version-1.14.0.jar:?]
        at cn.nukkit.Server.tick(Server.java:1124) [Nukkit-Version-1.14.0.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:903) [Nukkit-Version-1.14.0.jar:?]
        at cn.nukkit.Server.start(Server.java:880) [Nukkit-Version-1.14.0.jar:?]
        at cn.nukkit.Server.<init>(Server.java:565) [Nukkit-Version-1.14.0.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) [Nukkit-Version-1.14.0.jar:?]
Caused by: java.lang.NullPointerException
        at NukkitDB.NukkitDB.getDatabase(NukkitDB.java:125) ~[?:?]
        at NukkitDB.NukkitDB.query(NukkitDB.java:46) ~[?:?]
        at TelegramUI.Handler.DatabaseHandler.query(DatabaseHandler.java:14) ~[?:?]
        at TelegramUI.Events.FormResponseEvent.onFormSubmit(FormResponseEvent.java:116) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_202]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_202]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_202]
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[Nukkit-Version-1.14.0.jar:?]
        ... 16 more"

why it plugin?

**Comment by OwnerSCIFahrul** [comment]
Hey please answer!

**Comment by Atm85** [comment]
Hi, sorry. For some reason I want notified of this issue. I'll see what I can do.

**Comment by Atm85** [comment]
The error might be the cause that your `config.yml` is empty?

**Comment by GoodLucky777** [comment]
I have same error too!

config.yml have no problem.

`22:04:20 [FATAL] "cn.nukkit.event.player.PlayerFormRespondedEvent" 이벤트를 "TelegramUI v1.0.0"에 전달할 수 없습니다: TelegramUI.Events.FormResponseEvent에서의 null
22:04:20 [ERROR] Throwing
cn.nukkit.utils.EventException: null
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:2610) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_242]
        at cn.nukkit.network.Network.processPackets(Network.java:197) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.Network.processBatch(Network.java:180) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:2092) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:68) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.Network.processInterfaces(Network.java:83) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tick(Server.java:1126) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:905) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.start(Server.java:882) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:567) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit-1.0-SNAPSHOT.jar:?]
Caused by: java.lang.NullPointerException
        at TelegramUI.Events.FormResponseEvent.onFormSubmit(FormResponseEvent.java:104) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[nukkit-1.0-SNAPSHOT.jar:?]
        ... 16 more`

**Comment by GoodLucky777** [comment]
My config.yml was

database: networkStorage
collection: TelegramUI

**Comment by OwnerSCIFahrul** [comment]
What is my NukkitDB plugin config wrong?
config.yml:
# if using mongodb atlas
uri: "mongodb"

# if database is run on a local machine
host: ""
port: ""

**Comment by Atm85** [comment]
You need to get a connection string from mongodb atlats

**Comment by OwnerSCIFahrul** [comment]
write what

**Comment by Atm85** [comment]
Go to:
https://www.mongodb.com/cloud/atlats

1 sign up

2 create a cluster

3 get connecting string

4 download mongodb compas

5 enter connecting string into compas

6 in compass, create database with collection ( remember the names )

7 copy the connection string again but this time paste it into NukkitDB config ( uri )

8 in TellegramUI plugin, enter your database and collection names

**Comment by GoodLucky777** [comment]
What is wrong with me? My config.yml was
```
database: networkStorage
collection: TelegramUI
```

and NukkitDB config.yml was
```
if using mongodb atlas
uri: "mongodb://admin:password@127.0.0.1"

# if database is run on a local machine
host: ""
port: ""
~
~
```

**Comment by GoodLucky777** [comment]
And db was working

**Comment by Atm85** [comment]
> And db was working

Your saying that you ARE able to connect to other app such as mongodb atlats WHILE you are not able to connect from the plugin?

**Comment by GoodLucky777** [comment]
DB and NukkitDB is connected and work fine.
DB have no problem or error. And NukkitDB plugin too.
But I have that error.

**Comment by Atm85** [comment]
Ok, I looked more closely at the error and it looks like the error is caused by clicking a button in the form. 

Do you know which form it was?

**Comment by OwnerSCIFahrul** [comment]
hey i have problem: http://prntscr.com/qz3cc6
why "Server selection timed out after 30000 ms" connect Cluster with mongodb compass? please give me video tutorial you, i dont understand

**Comment by Atm85** [comment]
I do have a video tutorial, but I haven't Rd Ted and posted it yet

**Comment by OwnerSCIFahrul** [comment]
please quickly post a video about mongodb

**Comment by GoodLucky777** [comment]
It was a form asking if you would like to send DM or mail.
When I pressed Send Mail button, I got an error.
Also, when I pressed Send DM button, I got an error. In addition, I think something is wrong with DM button because I just pressed that button, but both come out. Mail form and DM form. (Issue #5)

**Comment by OwnerSCIFahrul** [comment]
hey iAtomPlaza , ready mongodb video tutorial? give me..

**Comment by Atm85** [comment]
I apologize for late reply, I have been working on many bug fixes across multiple of my plugins.

Do try this rewritten version now released
https://nukkitx.com/resources/telegramui.368/

( Make sure to also get the latest version of all the dependencies as they were also updated )

If you come across any other issues, do open another support ticket!
