### ISSUE TITLE
Error Again :(

### ISSUE THREAD

**Issue by GoodLucky777** [FoxValleyMC/TelegramUI#9]
17:57:25 [FATAL] "cn.nukkit.event.player.PlayerJoinEvent" 이벤트를 "TelegramUI v2.2.0"에 전달할 수 없습니다: TelegramUI.Events.JoinEvent에서의 null
17:57:25 [ERROR] Throwing
cn.nukkit.utils.EventException: null
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Player.doFirstSpawn(Player.java:878) [nukkit-1.0-SNAPSHOT.jar:?]                                                                                                                       at cn.nukkit.Player.sendNextChunk(Player.java:839) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Player.checkNetwork(Player.java:1855) [nukkit-1.0-SNAPSHOT.jar:?]                                                                                                                      at cn.nukkit.Server.tick(Server.java:1146) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:911) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.start(Server.java:888) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:573) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit-1.0-SNAPSHOT.jar:?]
Caused by: java.lang.NullPointerException
        at NukkitDB.Provider.MongoDB.getDatabase(MongoDB.java:55) ~[?:?]
        at NukkitDB.Provider.MongoDB.getCollection(MongoDB.java:64) ~[?:?]
        at TelegramUI.Events.JoinEvent.onJoin(JoinEvent.java:31) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[nukkit-1.0-SNAPSHOT.jar:?]                                                                                           ... 10 more

And this error occur PlayerAPI too.

17:57:25 [FATAL] "cn.nukkit.event.player.PlayerJoinEvent" 이벤트를 "PlayerAPI v2.0.1"에 전달할 수 없습니다: PlayerAPI.Main에서의 null
17:57:25 [ERROR] Throwing
cn.nukkit.utils.EventException: null
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Player.doFirstSpawn(Player.java:878) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Player.sendNextChunk(Player.java:839) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Player.checkNetwork(Player.java:1855) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tick(Server.java:1146) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:911) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.start(Server.java:888) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:573) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit-1.0-SNAPSHOT.jar:?]
Caused by: java.lang.NullPointerException
        at NukkitDB.Provider.MongoDB.getDatabase(MongoDB.java:55) ~[?:?]
        at NukkitDB.Provider.MongoDB.getCollection(MongoDB.java:64) ~[?:?]
        at PlayerAPI.Main.onJoin(Main.java:49) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[nukkit-1.0-SNAPSHOT.jar:?]
        ... 10 more

**Comment by Atm85** [comment]
Do you know what you were doing that caused the error?

**Comment by Atm85** [comment]
try deleting the config so a new one will generate, this error could be the cause of an outdated config as i updated the plugins with new config data

**Comment by GoodLucky777** [comment]
i delete all of config files and change it to
```
use-MongoDB: true
collection: TelegramUI
```
but error

**Comment by Atm85** [comment]
Did you also generat a new config for NukkitDB plugin as well?

**Comment by GoodLucky777** [comment]
I reset NukkitDB config, it worked! Thank you!
